### PR TITLE
Minor markdown formatting

### PR DESCRIPTION
**Pull request by geoffreymcgill**
Nice docs. 

Noticed a few locations to improve the consistency of the markdown formatting, plus wrapping the `<details>` in a Panel component. 

Hope this helps.

### CODE REVIEW

**Comment by geoffreymcgill** [comment]
Would also be nice to add a link to the docs website from the repo. 

https://www.postmanlabs.com/postman-flows/

Screen Shot 2022-01-25 at 3 10 13 PM

**Comment by saswatds** [comment]
Thanks @geoffreymcgill, I will review and merge this.

**Comment by saswatds** [comment]
Hey @geoffreymcgill, really sorry but we have a merge conflict here. Everything looks good. If you can resolve this, I will merge this PR.

**Comment by geoffreymcgill** [comment]
Conflict has been resolved. Should be good to go now. Hope this helps.

**Pull request merged**
